apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: objectbucketclaims.objectbucket.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.storageClassName
    description: StorageClass
    name: StorageClass
    type: string
  - JSONPath: .status.phase
    description: Phase
    name: Phase
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: objectbucket.io
  names:
    kind: ObjectBucketClaim
    listKind: ObjectBucketClaimList
    plural: objectbucketclaims
    singular: objectbucketclaim
  scope: Namespaced
  subresources: {}
  validation:
    openAPIV3Schema:
      description: ObjectBucketClaim is the Schema for the objectbucketclaims API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ObjectBucketClaimSpec defines the desired state of ObjectBucketClaim
          properties:
            additionalConfig:
              additionalProperties:
                type: string
              description: AdditionalConfig gives providers a location to set proprietary
                config values (tenant, namespace, etc)
              type: object
            bucketClassNamespace:
              type: string
            bucketName:
              description: BucketName (not recommended) the name of the bucket.  Caution!
                In-store bucket names may collide across namespaces.  If you define
                the name yourself, try to make it as unique as possible.
              type: string
            generateBucketName:
              description: GenerateBucketName (recommended) a prefix for a bucket
                name to be followed by a hyphen and 5 random characters. Protects
                against in-store name collisions.
              type: string
            objectBucketName:
              description: ObjectBucketName is the name of the object bucket resource.  This
                is the authoritative determintaion for binding.
              type: string
            storageClassName:
              description: BucketClass names the BucketClass object indirectly declares
                the desired plugin and parameters
              type: string
          required:
          - bucketClassNamespace
          - objectBucketName
          - storageClassName
          type: object
        status:
          description: ObjectBucketClaimStatus defines the observed state of ObjectBucketClaim
          properties:
            phase:
              description: ObjectBucketClaimStatusPhase is set by the controller to
                save the state of the provisioning process.
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
