apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosi-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cosi-controller
  template:
    metadata:
      labels:
        name: cosi-controller
    spec:
      serviceAccountName: cosi-prototype-driver
      containers:
        - name: cosi-controller
          # Replace this with the built image name
          image: cosi.io/controller
          command:
          - cosi-prototype-driver
          args:
          - '--zap-devel'
          imagePullPolicy: Never
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cosi-controller"
